import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data } = useSession();
  return (
    <>
      <Head>
        <title>Okos otthon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!data?.user ? (
          <button
            className="btn-ghost btn-xs btn"
            onClick={() => void signIn()}
          >
            Bejelentkezés
          </button>
        ) : (
          <button
            className="btn-ghost btn-xs btn"
            onClick={() => void signOut()}
          >
            Kijelentkezés
          </button>
        )}
      </main>
    </>
  );
};

export default Home;
